name: Auto Reset All JSON Files Every 6 Hours

on:
  schedule:
    - cron: "0 */6 * * *"   # Runs every 6 hours (00:00, 06:00, 12:00, 18:00 UTC)
  workflow_dispatch:         # Optional: manual run

jobs:
  reset:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Reset all JSON files
        run: |
          for file in *.json; do
            echo "Resetting $file..."
            cat > "$file" <<'EOF'
            [
              {
                "events": [
                  {
                    "name": "Join YoSinTV Telegram Channel",
                    "link": "https://t.me/yosintvlive"
                  }
                ],
                "styles": {
                  "livee": "display: flex; justify-content: center; align-items: center; text-decoration: none; color: inherit; margin: 5px 0; padding: 10px; border: 2px solid #000; border-radius: 5px; cursor: pointer; transition: box-shadow 0.3s ease; background-color: red; color: white;",
                  "liveeHover": "box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2);",
                  "liveeName": "flex: 2; text-align: center; color: white; font-weight: bold;"
                }
              }
            ]
            EOF
          done

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add *.json
          git commit -m "Auto reset all JSON files to base template (6-hour schedule)" || echo "No changes to commit"
          git push
